import re

cut_table = re.compile(r"\<table.*?<\/table>")
cut_list = re.compile(r"<li .*?<\/li>")
cut_sup = re.compile(r"<sup.*?<\/sup>")
cut_note = re.compile(r"<div role=\"note\".*?<\/div>")

cut_first_table = re.compile(r"(.*?)(\*\*.+?\*\*.+)")
cut_references = re.compile(r"(.*?)(## References.*)")
cut_references2 = re.compile(r"(.*?)\*\[.*\]: Deuxième.*")
cut_references_fr = re.compile(r"(.*?)(## Notes et références.*)")
cut_references_fr2 = re.compile(r"(.*?)(## Sources.*)")
cut_references_zh = re.compile(r"(.*?)(## 参考.*)")
cut_references_zh2 = re.compile(r"(.*?)(## 參考.*)")
cut_references_ru = re.compile(r"(.*?)(## Примечания.*)")
cut_references_es = re.compile(r"(.*?)(## Referencias.*)")
cut_references_ko = re.compile(r"(.*?)(## 각주*)")

second_heading = re.compile(r"#{2}\s{1}(.*?)\s{2}")
second_heading2 = re.compile(r"#{2}\s{1}(.*?)\s{1}(\s|$)")
third_heading = re.compile(r"#{3}\s{1}(.*?)\s{2}")
third_heading2 = re.compile(r"#{3}\s{1}(.*?)\s{1}(\s|$)")
fourth_heading = re.compile(r"#{4}\s{1}(.*?)\s{2}")
fourth_heading2 = re.compile(r"#{4}\s{1}(.*?)\s{1}(\s|$)")
emphasis = re.compile(r"_(.*?)_")
double_paren = re.compile(r"\\\\\(.*?\\\\\)")
paren = re.compile(r"[\(（].*?[\)）]")
# paren_zh = re.compile(r"（.*?）")
paren_zh2 = re.compile(r"《(.*?)》")
paren_fr = re.compile(r"«(.*?)»")
bold  = re.compile(r"\*\*(.+?)\*\*")
punctuations = re.compile(r"([?!,.\":;—])")
all_spaces = re.compile(r"\s+")
alert = re.compile(r"<div class=\"(.*?)incompl(.*?)\"(.*?)<\/div>")

second_heading_separation = re.compile(r"\s#{2}\s{1}(.*?)\s{2}(.*?)(?=\s+#{2}\s+|$)")
third_heading_separation = re.compile(r"([^#])+#{3}\s{1}(.*?)\s{2}(.*?)(?=\s#{3}\s|$)")
final_third_heading_separation = re.compile(r"#{3}\s{1}(.*?)(?=$)")
fourth_heading_separation = re.compile(r"\s#{4}\s{1}(.*?)\s{2}(.*?)(?=\s+#{4}\s+)")

link = re.compile(r"\[(.*)?\]\(.*?\)")
cut_first_table = re.compile(r"(.*?)(\*\*.+?\*\*.+)")
link_number = re.compile(r"\[[0-9]+\]")